import type { Metadata } from "next";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";
import "./globals.css";
import SideNavWrapper from "@/components/Layout/SideNavWrapper";

const SideNav = dynamic(() => import("@/components/Layout/SideNav"));
const Container = dynamic(() => import("@/components/Layout/Container"));

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container>
          <SideNavWrapper />
          {children}
        </Container>
      </body>
    </html>
  );
}
